# Default values for webapp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  # Overrides the image tag whose default is the chart appVersion.
  tag: 2.1-4f01-rc
  env:
    - name: HOSTNAME
      value: 2.1-4f01-rc
